apply plugin: 'com.android.library'

android {
    namespace 'com.starseed.speechtotext'
    compileSdkVersion 36
    buildToolsVersion '36.1.0'
    defaultConfig {
        minSdkVersion 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.games:games-activity:4.4.0'
    testImplementation 'junit:junit:4.12'
    api 'androidx.appcompat:appcompat:1.4.2'
    api 'com.google.android.material:material:1.6.1'

    compileOnly 'com.google.firebase:firebase-messaging:25.0.1'


    //compileOnly files('libs/firebase-messaging-unity-13.9.0.aar')

    compileOnly files('libs/firebase-messaging-cpp.aar')



    compileOnly files('libs/classes.jar')
    //implementation files('libs/unity-classes.jar');
}

//task to delete the old jar
task deleteOldJar(type: Delete) {
    delete 'release/SpeechToTextPlugin.jar'
}

//task to export content as jar
task exportJar(type: Copy) {
    from('build/intermediates/aar_main_jar/release/syncReleaseLibJars/')
    into('release/')
    include('classes.jar')
    rename('classes.jar', 'SpeechToTextPlugin.jar')
}

exportJar.dependsOn(deleteOldJar, build)
